# Generated by Django 5.2.7 on 2025-10-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_intervieweeform_email_intervieweeform_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervieweeform',
            name='mobile_no',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
