# Generated by Django 5.2.7 on 2025-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0004_alter_intervieweeform_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervieweeform',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
