# Generated by Django 5.2.7 on 2025-10-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_alter_intervieweeform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweeform',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='intervieweeform',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
