# Generated by Django 5.2.7 on 2025-10-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_intervieweeform_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweeform',
            name='reference_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
