# Generated by Django 5.2.7 on 2025-10-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0007_intervieweeform_reference_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervieweeform',
            old_name='reference_by',
            new_name='reference',
        ),
    ]
