# Generated by Django 5.2.7 on 2025-10-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0008_rename_reference_by_intervieweeform_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweeform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=10),
        ),
    ]
