# Generated by Django 5.2.7 on 2025-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0009_intervieweeform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervieweeform',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
